# Generated by Django 3.2 on 2021-05-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('l_name', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='Емейл')),
                ('subject', models.CharField(blank=True, max_length=50, verbose_name='Тема')),
                ('message', models.TextField(blank=True, max_length=500, verbose_name='Сообщение')),
            ],
            options={
                'verbose_name': 'Сообщение с сайта',
                'verbose_name_plural': 'Сообщения с сайта',
            },
        ),
        migrations.AlterField(
            model_name='head',
            name='title_on_image',
            field=models.CharField(blank=True, max_length=50, verbose_name='Заголовок на главном фото'),
        ),
    ]
